### ISSUE TITLE
UI error, menu bar is disappeared

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/SUMOBugs#17]
**Describe the bug:** 
UI error, menu bar is disappeared

 **Steps to reproduce:** 
1. Update Firefox old version to Firefox 69
2. Open Firefox 69
3. Check menu bar is appear.
4. Close Firefox 69 and try step 3

 **Expected behavior:** 
Menu bar is appeared.

 **Actual behavior:** 
Menu bar is not appeared.

 **Device information:** 
Operating system not mentioned.
Firefox version: 69

 **Additional context:** 
No

 **Reporter:** 
@milindalaknath

**Comment by rtanglao** [comment]
@kelimuttu i can't reproduce this! is it mac os x, linux or windows? and if so what version of os x, linux or windows
