### ISSUE TITLE
Videos on Facebook timeline don't work correctly on Firefox preview

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/SUMOBugs#18]
**Describe the bug:** 
Videos on Facebook timeline don't work correctly on Firefox preview

 **Steps to reproduce:** 
1)Start Firefox preview by clicking on the application icon
2)Write www.Facebook.com to the url
3)scroll down the timeline till I found a video
4) click the video play icon.

 **Expected behavior:** 
The video should be played correctly with sounds and images

 **Actual behavior:** 
The Facebook video played correctly for 2 seconds and then the video sound continued playing but the image(frames) stopped. I was able to hear the sound but  did not  able to watch anything.

 **Device information:** 
Firefox preview , Android

 **Additional context:** 
Videos are sometimes played well specially when I start Firefox preview once  I restart the  device

 **Reporter:** 
@yamamashakaa

**Comment by rtanglao** [comment]
hi @kelimuttu i can't reproduce this problem. facebook native videos work fine for me on firefox preview, android 9, note 8. perhaps ask for the android version, and handset and a specific facebook video link?
